export const PROFILE_FIELDS_PROJECTION = {
  SUMMARY: {
    _id: 1,
    username: 1,
    email: 1,
    firstName: 1,
    lastName: 1,
    role: 1,
    profilePictureUrl: 1,
    bio: 1,
    profileUrls: 1,
    isVerified: 1,
  },
  SUMMARY_WITH_CONNECTIONS: {
    _id: 1,
    username: 1,
    email: 1,
    firstName: 1,
    lastName: 1,
    role: 1,
    profilePictureUrl: 1,
    bio: 1,
    profileUrls: 1,
    isVerified: 1,
    connections: 1,
    connection: 1,
  },
  DETAIL: {
    _id: 1,
    username: 1,
    email: 1,
    firstName: 1,
    lastName: 1,
    role: 1,
    profilePictureUrl: 1,
    bio: 1,
    profileUrls: 1,
    isVerified: 1,
    connections: 1,
    connection: 1,
    skills: 1,
    educations: 1,
    certifications: 1,
    achievements: 1,
    experiences: 1,
    visibility: 1,
    socialMediaLinks: 1,
  },
} as const;
