/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as authVerifyOtpImport } from './routes/(auth)/verify-otp'
import { Route as authSignupImport } from './routes/(auth)/signup'
import { Route as authSigninImport } from './routes/(auth)/signin'
import { Route as ProfileIdentifierRouteImport } from './routes/profile/$identifier/route'
import { Route as projectProjectsProfileUrlImport } from './routes/(project)/projects.$profileUrl'
import { Route as projectProjectNewImport } from './routes/(project)/project.new'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authVerifyOtpRoute = authVerifyOtpImport.update({
  id: '/(auth)/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRoute,
} as any)

const authSignupRoute = authSignupImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const authSigninRoute = authSigninImport.update({
  id: '/(auth)/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIdentifierRouteRoute = ProfileIdentifierRouteImport.update({
  id: '/profile/$identifier',
  path: '/profile/$identifier',
  getParentRoute: () => rootRoute,
} as any)

const projectProjectsProfileUrlRoute = projectProjectsProfileUrlImport.update({
  id: '/(project)/projects/$profileUrl',
  path: '/projects/$profileUrl',
  getParentRoute: () => rootRoute,
} as any)

const projectProjectNewRoute = projectProjectNewImport.update({
  id: '/(project)/project/new',
  path: '/project/new',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/profile/$identifier': {
      id: '/profile/$identifier'
      path: '/profile/$identifier'
      fullPath: '/profile/$identifier'
      preLoaderRoute: typeof ProfileIdentifierRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/verify-otp': {
      id: '/(auth)/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof authVerifyOtpImport
      parentRoute: typeof rootRoute
    }
    '/(project)/project/new': {
      id: '/(project)/project/new'
      path: '/project/new'
      fullPath: '/project/new'
      preLoaderRoute: typeof projectProjectNewImport
      parentRoute: typeof rootRoute
    }
    '/(project)/projects/$profileUrl': {
      id: '/(project)/projects/$profileUrl'
      path: '/projects/$profileUrl'
      fullPath: '/projects/$profileUrl'
      preLoaderRoute: typeof projectProjectsProfileUrlImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile/$identifier': typeof ProfileIdentifierRouteRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/verify-otp': typeof authVerifyOtpRoute
  '/project/new': typeof projectProjectNewRoute
  '/projects/$profileUrl': typeof projectProjectsProfileUrlRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile/$identifier': typeof ProfileIdentifierRouteRoute
  '/signin': typeof authSigninRoute
  '/signup': typeof authSignupRoute
  '/verify-otp': typeof authVerifyOtpRoute
  '/project/new': typeof projectProjectNewRoute
  '/projects/$profileUrl': typeof projectProjectsProfileUrlRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/profile/$identifier': typeof ProfileIdentifierRouteRoute
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/verify-otp': typeof authVerifyOtpRoute
  '/(project)/project/new': typeof projectProjectNewRoute
  '/(project)/projects/$profileUrl': typeof projectProjectsProfileUrlRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile/$identifier'
    | '/signin'
    | '/signup'
    | '/verify-otp'
    | '/project/new'
    | '/projects/$profileUrl'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile/$identifier'
    | '/signin'
    | '/signup'
    | '/verify-otp'
    | '/project/new'
    | '/projects/$profileUrl'
  id:
    | '__root__'
    | '/'
    | '/profile/$identifier'
    | '/(auth)/signin'
    | '/(auth)/signup'
    | '/(auth)/verify-otp'
    | '/(project)/project/new'
    | '/(project)/projects/$profileUrl'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileIdentifierRouteRoute: typeof ProfileIdentifierRouteRoute
  authSigninRoute: typeof authSigninRoute
  authSignupRoute: typeof authSignupRoute
  authVerifyOtpRoute: typeof authVerifyOtpRoute
  projectProjectNewRoute: typeof projectProjectNewRoute
  projectProjectsProfileUrlRoute: typeof projectProjectsProfileUrlRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileIdentifierRouteRoute: ProfileIdentifierRouteRoute,
  authSigninRoute: authSigninRoute,
  authSignupRoute: authSignupRoute,
  authVerifyOtpRoute: authVerifyOtpRoute,
  projectProjectNewRoute: projectProjectNewRoute,
  projectProjectsProfileUrlRoute: projectProjectsProfileUrlRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/profile/$identifier",
        "/(auth)/signin",
        "/(auth)/signup",
        "/(auth)/verify-otp",
        "/(project)/project/new",
        "/(project)/projects/$profileUrl"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/profile/$identifier": {
      "filePath": "profile/$identifier/route.tsx"
    },
    "/(auth)/signin": {
      "filePath": "(auth)/signin.tsx"
    },
    "/(auth)/signup": {
      "filePath": "(auth)/signup.tsx"
    },
    "/(auth)/verify-otp": {
      "filePath": "(auth)/verify-otp.tsx"
    },
    "/(project)/project/new": {
      "filePath": "(project)/project.new.tsx"
    },
    "/(project)/projects/$profileUrl": {
      "filePath": "(project)/projects.$profileUrl.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
