name: CI Pipeline

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "LICENSE"
      - ".gitignore"

  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "LICENSE"
      - ".gitignore"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.4.1

      - name: Install all dependencies
        run: pnpm install

      - name: Build all packages
        run: |
          pnpm build:shared
          pnpm build:server

      - name: Build client
        run: pnpm build:client
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
